const chooseResponseQuestions = [
  { id:1, heard:"I can't believe the professor cancelled class again without giving us any notice.", options:["That's great — more free time for us!","I know, it's really frustrating when that happens at the last minute.","The professor teaches three courses this semester.","Class starts at 9 AM every Monday."], answer:1 },
  { id:2, heard:"Do you know if the library has extended hours during finals week?", options:["The library has a great collection of science books.","I'm not sure, but you could check their website for the schedule.","Finals week is usually in December.","I prefer studying at the student centre."], answer:1 },
  { id:3, heard:"I've been working on this essay for three days and I'm still not happy with it.", options:["Essays are usually due at midnight.","Three days is a long time to work on something.","Have you tried the writing centre? They give really helpful feedback.","What class is the essay for?"], answer:2 },
  { id:4, heard:"Excuse me, is this seat taken?", options:["The chairs are made of plastic.","No, go ahead — it's free.","I usually sit by the window.","The room holds about 30 people."], answer:1 },
  { id:5, heard:"I left my notebook in the lecture hall after class. What should I do?", options:["Notebooks are available at the campus shop.","You should go back and check, or ask the department office — they often collect lost items.","Lecture halls are usually locked after 6 PM.","What subject was the lecture on?"], answer:1 },
  { id:6, heard:"I'm thinking about dropping my psychology class. It's much harder than I expected.", options:["Psychology is a popular subject.","The drop deadline is usually two weeks into the semester.","That's a tough decision. Have you spoken to your advisor about it first?","You could try a different professor next semester."], answer:2 },
  { id:7, heard:"I heard there's a guest lecture on climate science tomorrow. Are you going?", options:["Climate change is an important topic.","I didn't know about it — what time does it start?","The science building is on the east side of campus.","Guest lectures are usually recorded."], answer:1 },
  { id:8, heard:"Could you help me understand this formula? I've read it three times and I'm still confused.", options:["Formulas can be tricky.","Sure, let me walk you through it step by step.","You should ask the professor directly.","That formula is on page 47."], answer:1 },
  { id:9, heard:"The campus café was completely out of coffee this morning. Can you believe it?", options:["Coffee has a lot of caffeine.","That must have been rough — especially before an early lecture.","The café opens at 7:30 AM.","I prefer tea anyway."], answer:1 },
  { id:10, heard:"I submitted my assignment five minutes after the deadline. Do you think the professor will accept it?", options:["The assignment was about urban planning.","It depends on the professor. I'd send a quick email explaining what happened and apologise.","Online submissions close automatically.","You should always save your work."], answer:1 },
  { id:11, heard:"I'm not sure whether to take statistics or research methods next semester.", options:["Both are offered in the spring.","Both are useful, but if you plan to do your own research, methods might be more directly helpful.","Statistics is a required course for some majors.","You should check the course catalogue."], answer:1 },
  { id:12, heard:"My group members haven't responded to my messages about the project at all.", options:["Group projects can be challenging.","That's really frustrating. Have you tried a different platform, or spoken to your professor about it?","The project is worth 30% of the final grade.","You could do the whole project yourself."], answer:1 },
  { id:13, heard:"I just found out I passed the scholarship interview. I'm so relieved!", options:["Scholarship applications require a lot of documents.","That's wonderful news — congratulations! All that preparation really paid off.","How many candidates were there?","Scholarships usually cover tuition only."], answer:1 },
  { id:14, heard:"Sorry I'm late — the bus was absolutely packed and it took forever.", options:["The bus schedule changes in winter.","Don't worry about it. You haven't missed much — we just started.","There's a parking lot near the building.","Public transport is usually unreliable."], answer:1 },
  { id:15, heard:"I keep falling asleep during evening lectures. Is that normal?", options:["Evening lectures end at 9 PM.","It's pretty common. Try getting some sleep before class, or sit closer to the front to stay engaged.","The lighting in that room is quite dim.","Some professors allow coffee in class."], answer:1 }
];
